# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  test:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - cargo test -- --nocapture

  run:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - cargo run
